### ISSUE TITLE
Game crashes when trying to load a save; mods: 'Wandering Minibosses' + 'Together in Spire'

### ISSUE THREAD

**Issue by seowth** [erasels/wanderingMiniBosses#53]
Hello, 

As per the subject:-
Only mods tested: '[Wandering Minibosses](https://steamcommunity.com/sharedfiles/filedetails/?id=1974151303&searchtext=minibosses)' & ['Together in Spire'](https://steamcommunity.com/sharedfiles/filedetails/?id=2384072973&searchtext=together) (both load-order orientations)

'Together in Spire' is a concurrent multiplayer mod.

- The mods largely work fine together(*see the last picture @ very bottom of the page) but if you try to load-save using TiS' Multiplayer mode, it will result in a crash.
- TiS' MP load-save (screen that looks like this)  crashes when the save is clicked:

![20230118015030_1](https://user-images.githubusercontent.com/87141050/213116210-4f66474b-d82f-467e-a77f-8019bb3b2227.jpg)

- Load-saving in SP ("Singleplayer - Continue") seems to work normally; I saved and exited a game when I found the Nemesis floor...loaded back into the same floor and the nemesis spawned again. 

![20230118015005_1](https://user-images.githubusercontent.com/87141050/213116353-62e6fdee-8637-4b21-bc96-33584402e15a.jpg)

![20230118015445_1](https://user-images.githubusercontent.com/87141050/213116540-cd51b53d-9410-4780-97c2-f6457e344d27.jpg)

I mentioned the crash in the [TIS Discord](https://discord.com/invite/uQGDpDr) and Draco the developer replied that if "...the game saving [is modified] to save their own data which is inherently incompatible with my mod because I completely override the base game save...probably require custom patches in the future"

I have also shared the link to this issue for information.

Below are the two crash logs; "Clean shutdown successful" ONLY when WMbosses is loaded before TIS

************************************(1) Crash log [TIS loaded before WMbosses]: **********************************

>00:27:49.771 INFO core.CardCrawlGame> Exception occurred in CardCrawlGame render method!
00:27:49.771 ERROR core.CardCrawlGame> Exception caught
java.lang.NullPointerException: null
	at wanderingMiniBosses.WanderingminibossesMod$3.onLoad(WanderingminibossesMod.java:222) ~[wanderingMiniBosses.jar:?]
	at wanderingMiniBosses.WanderingminibossesMod$3.onLoad(WanderingminibossesMod.java:214) ~[wanderingMiniBosses.jar:?]
	at basemod.abstracts.CustomSavable.onLoadRaw(CustomSavable.java:42) ~[BaseMod.jar:?]
	at basemod.patches.com.megacrit.cardcrawl.core.CardCrawlGame.LoadPlayerSaves.Postfix(LoadPlayerSaves.java:89) ~[BaseMod.jar:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.loadPlayerSave(CardCrawlGame.java:1245) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:801) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:423) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126) [?:?]
Controllers: removed manager for application, 0 managers active
00:27:49.833 INFO core.CardCrawlGame> PAUSE()
00:27:49.833 INFO core.CardCrawlGame> Game shutting down...
00:27:49.833 INFO core.CardCrawlGame> Flushing saves to disk...
00:27:49.833 INFO core.CardCrawlGame> Shutting down controller handler...
00:27:49.833 INFO core.CardCrawlGame> Shutting down publisher integrations...
00:27:49.833 INFO helpers.FileSaver> Save thread interrupted!
00:27:49.834 INFO helpers.FileSaver> Save thread will die now.
00:27:49.834 INFO helpers.FileSaver> Save thread will die now.
2023-01-17 18:27:49,835 FileSaver ERROR An exception occurred processing Appender Console org.apache.logging.log4j.core.appender.AppenderLoggingException: java.lang.Error: Interrupted attempt to acquire write lock
	at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:165)
	at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:134)
	at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:125)
	at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:89)
	at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:542)
	at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:500)
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:483)
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:417)
	at org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:82)
	at org.apache.logging.log4j.core.Logger.log(Logger.java:161)
	at org.apache.logging.log4j.spi.AbstractLogger.tryLogMessage(AbstractLogger.java:2205)
	at org.apache.logging.log4j.spi.AbstractLogger.logMessageTrackRecursion(AbstractLogger.java:2159)
	at org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2142)
	at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:2017)
	at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1983)
	at org.apache.logging.log4j.spi.AbstractLogger.info(AbstractLogger.java:1320)
	at com.megacrit.cardcrawl.helpers.FileSaver.run(FileSaver.java:31)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.Error: Interrupted attempt to acquire write lock
	at javax.swing.text.AbstractDocument.writeLock(AbstractDocument.java:1349)
	at javax.swing.text.AbstractDocument.insertString(AbstractDocument.java:701)
	at javax.swing.text.PlainDocument.insertString(PlainDocument.java:130)
	at com.evacipated.cardcrawl.modthespire.ui.MessageConsole$ConsoleOutputStream.clearBuffer(MessageConsole.java:226)
	at com.evacipated.cardcrawl.modthespire.ui.MessageConsole$ConsoleOutputStream.handleAppend(MessageConsole.java:183)
	at com.evacipated.cardcrawl.modthespire.ui.MessageConsole$ConsoleOutputStream.flush(MessageConsole.java:154)
	at java.io.PrintStream.write(PrintStream.java:482)
	at org.apache.logging.log4j.core.util.CloseShieldOutputStream.write(CloseShieldOutputStream.java:53)
	at org.apache.logging.log4j.core.appender.OutputStreamManager.writeToDestination(OutputStreamManager.java:250)
	at org.apache.logging.log4j.core.appender.OutputStreamManager.flushBuffer(OutputStreamManager.java:283)
	at org.apache.logging.log4j.core.appender.OutputStreamManager.flush(OutputStreamManager.java:294)
	at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.directEncodeEvent(AbstractOutputStreamAppender.java:199)
	at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.tryAppend(AbstractOutputStreamAppender.java:190)
	at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.append(AbstractOutputStreamAppender.java:181)
	at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:161)
	... 17 more
>
>00:27:49.839 INFO core.CardCrawlGame> Flushing logs to disk. Clean shutdown successful.
Game crashed.
Version Info:
> - Java version (1.8.0_144)
> - Slay the Spire (12-18-2022)
> - ModTheSpire (3.30.2)
>Mod list:
> - basemod (5.48.0)
> - stslib (2.7.0)
> - spireTogether (3.0.11)
> - wanderingMiniBosses (1.1.3)
>
>Mods in stacktrace:
 >- wanderingMiniBosses (1.1.3)
Cause:
java.lang.NullPointerException
	at wanderingMiniBosses.WanderingminibossesMod$3.onLoad(WanderingminibossesMod.java:222)
	at wanderingMiniBosses.WanderingminibossesMod$3.onLoad(WanderingminibossesMod.java:214)
	at basemod.abstracts.CustomSavable.onLoadRaw(CustomSavable.java:42)
	at basemod.patches.com.megacrit.cardcrawl.core.CardCrawlGame.LoadPlayerSaves.Postfix(LoadPlayerSaves.java:89)
	at com.megacrit.cardcrawl.core.CardCrawlGame.loadPlayerSave(CardCrawlGame.java:1245)
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:801)
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:423)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)

************************************(2) Crash log [WMbosses loaded before TIS]: **********************************

>00:51:55.879 INFO core.CardCrawlGame> Game shutting down...
00:51:55.880 INFO core.CardCrawlGame> Flushing saves to disk...
00:51:55.880 INFO core.CardCrawlGame> Shutting down controller handler...
00:51:55.881 INFO core.CardCrawlGame> Shutting down publisher integrations...
00:51:55.881 INFO helpers.FileSaver> Save thread interrupted!
00:51:55.881 INFO helpers.FileSaver> Save thread will die now.
00:51:55.885 INFO core.CardCrawlGame> Flushing logs to disk. Clean shutdown successful.

>  Game crashed.
> Version Info:
> - Java version (1.8.0_144)
> - Slay the Spire (12-18-2022)
> - ModTheSpire (3.30.2)
> Mod list:
> - basemod (5.48.0)
> - stslib (2.7.0)
> - wanderingMiniBosses (1.1.3)
> - spireTogether (3.0.11)

> Mods in stacktrace:
> - wanderingMiniBosses (1.1.3)
Cause:
java.lang.NullPointerException
	at wanderingMiniBosses.WanderingminibossesMod$3.onLoad(WanderingminibossesMod.java:222)
	at wanderingMiniBosses.WanderingminibossesMod$3.onLoad(WanderingminibossesMod.java:214)
	at basemod.abstracts.CustomSavable.onLoadRaw(CustomSavable.java:42)
	at basemod.patches.com.megacrit.cardcrawl.core.CardCrawlGame.LoadPlayerSaves.Postfix(LoadPlayerSaves.java:89)
	at com.megacrit.cardcrawl.core.CardCrawlGame.loadPlayerSave(CardCrawlGame.java:1245)
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:801)
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:423)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)

- On a side note... is the Thief supposed to be flying and this small? He appeared like this in multiple tests:

![20230118015255_1](https://user-images.githubusercontent.com/87141050/213120735-62f28b5e-f140-4e52-823e-71f51e401dc1.jpg)

- Seems like he is using the same positioning as the Staring Abyss?

![20230116122351_1](https://user-images.githubusercontent.com/87141050/213124175-2bf52ef6-f504-4897-8fe5-1db88a2e9e0e.jpg)

- *Note that aside from TiS load-saving, the nemeses seem to work fine in MP (pending verification w/ another player)

![Minibosses working w mods in MP](https://user-images.githubusercontent.com/87141050/213125915-91a088b7-0324-4ed3-bd9e-f38a4a0740cd.jpg)

**Comment by erasels** [comment]
Hey, thanks for the detailed and thorough documentation. I'm currently really busy with the current anniversary project (which is going to be released later today) so I can't look at this right now but I'll take a look once things have calmed down a bit since it sounds like it works for the most part as long as you don't save and quit.

As for the Thief, yes, that's the "wanted" location, the contributor got lazy. These projects are a group effort and thus some submissions defer in quality, you can toggle the minibosses in the config (although, I don't know how this will influence your multiplayer experience if both people don't filter the same miniboss)

**Comment by seowth** [comment]
Thank you! 

> current anniversary project (which is going to be released later today)
_ How exciting! Good luck & congratulations _

**Comment by Draco9990** [comment]
Hey! Author of Together in Spire here, this thread was linked to me on my bug report page as well.

As I was quoted, I completely overhaul the saving system as I take the base StS saves and integrate them with extra MP data and save them in a completely different location. This fully affects all saving and loading functions, and I'm aware that it makes loading saves with a lot of mods completely incompatible. I'm currently still in the development of the main mod tho, so full mod compat is not on the list of short-term priorities. After I'm done with the main mod, I'll consider creating custom patches myself.

If you feel like you want to reach out to work on compat together, you can contact me on Discord at Draco9990#6626, but otherwise, you don't have to worry or treat this as an open bug, and I can handle it on my and at some future date :)

Congratz on the anniversary!

**Comment by erasels** [comment]
Oh, if it's a general issue and the mod is still in development with focus on other things, then I'd rather wait.
When you get around to it and need help/changes within this mod to make things easier, let me know!
